// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyM1bCfNXe-P6yCDsH4EMa1Vsm24GXAcQ',
    appId: '1:252477818911:web:75c208eb22f03825cbad2a',
    messagingSenderId: '252477818911',
    projectId: 'student-assistant-c2ea9',
    authDomain: 'student-assistant-c2ea9.firebaseapp.com',
    storageBucket: 'student-assistant-c2ea9.firebasestorage.app',
    measurementId: 'G-03F821FX4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQFL96ngUcHqQtFhMgqye5pd1GLhqttCk',
    appId: '1:252477818911:android:d5d145168db3485fcbad2a',
    messagingSenderId: '252477818911',
    projectId: 'student-assistant-c2ea9',
    storageBucket: 'student-assistant-c2ea9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4A2WRV1oyfwevgd4rsfFzNOkJ6cQdLto',
    appId: '1:252477818911:ios:31ab774e52a6f15bcbad2a',
    messagingSenderId: '252477818911',
    projectId: 'student-assistant-c2ea9',
    storageBucket: 'student-assistant-c2ea9.firebasestorage.app',
    iosBundleId: 'com.example.univerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4A2WRV1oyfwevgd4rsfFzNOkJ6cQdLto',
    appId: '1:252477818911:ios:31ab774e52a6f15bcbad2a',
    messagingSenderId: '252477818911',
    projectId: 'student-assistant-c2ea9',
    storageBucket: 'student-assistant-c2ea9.firebasestorage.app',
    iosBundleId: 'com.example.univerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyM1bCfNXe-P6yCDsH4EMa1Vsm24GXAcQ',
    appId: '1:252477818911:web:7c2db76da7d3b9f0cbad2a',
    messagingSenderId: '252477818911',
    projectId: 'student-assistant-c2ea9',
    authDomain: 'student-assistant-c2ea9.firebaseapp.com',
    storageBucket: 'student-assistant-c2ea9.firebasestorage.app',
    measurementId: 'G-7LP074HQDB',
  );
}
